#!/usr/bin/env python
import sys
import argparse
import subprocess
import re

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-o')
    parser.add_argument('-r', action='store_true')
    parser.add_argument('source')
    parser.add_argument('destination')
    return parser.parse_args()

def main(args):
    destination = re.match('\w+@\w+:(.+)',
                           args.destination).group(1)
    return subprocess.call('cp -r "{0}" "{1}"'.format(args.source,
                                                      destination),
                           shell=True)

if __name__ == "__main__":
    sys.exit(main(parse_args()))
