#!/usr/bin/env python
import sys
import argparse
import subprocess

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-t', action='store_true')
    parser.add_argument('-o', action='append')
    parser.add_argument('-p')
    parser.add_argument('host')
    parser.add_argument('cmd')
    return parser.parse_args()

def main(args):
    return subprocess.call(args.cmd, shell=True)

if __name__ == "__main__":
    sys.exit(main(parse_args()))
